name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      # Must match the version in Cargo.toml
      - run: cargo install cargo-pgrx --version 0.11.4 --locked --force
      - run: cargo pgrx init
      - run: just ci-test

  msrv:
    name: Test MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      - name: Read crate metadata
        id: metadata
        run: echo "rust-version=$(sed -ne 's/rust-version *= *\"\(.*\)\"/\1/p' Cargo.toml)" >> $GITHUB_OUTPUT
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.metadata.outputs.rust-version }}
          components: clippy,rustfmt
      # Must match the version in Cargo.toml
      - run: cargo install cargo-pgrx --version 0.11.4 --locked --force
      - run: cargo pgrx init
      - run: just ci-test-msrv

#  build:
#    name: Build ${{ matrix.target }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - target: aarch64-apple-darwin
#            os: macOS-14
#          - target: x86_64-apple-darwin
#            os: macOS-12
#          - target: x86_64-pc-windows-msvc
#            os: windows-latest
#          - target: x86_64-unknown-linux-gnu
#            os: ubuntu-latest
#    steps:
#      - uses: taiki-e/install-action@v2
#        with:
#          tool: just
#      - uses: actions/checkout@v4
#      - uses: Swatinem/rust-cache@v2
#        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
